### ISSUE TITLE
Lib không hoạt động!!!

### ISSUE THREAD

**Issue by trungthinhbo** [pth-1641/Comics-API#1]
Lib không hoạt động anh ơi.
Em tạo 1 nodeserver đơn giản rồi gọi hàm getGenres() thì gặp lỗi này (bản build: 2.8.5).
<img width="658" alt="Screen Shot 2023-07-29 at 21 16 21" src="https://github.com/pth-1641/Comics-API/assets/123989667/af617d82-1cca-43a5-be7d-d60c13084858">

**Comment by pth-1641** [comment]
@TrungThinhScorpius Update bản mới giúp mình nhé

**Comment by trungthinhbo** [comment]
> @TrungThinhScorpius Update bản mới giúp mình nhé

Triệu tim.

**Comment by trungthinhbo** [comment]
@pth-1641 lỗi tiếp anh ơi
