### ISSUE TITLE
Tìm kiếm truyện đề xuất 

### ISSUE THREAD

**Issue by Trung123580** [pth-1641/Comics-API#10]
/search-suggest?q={query} tìm kiếm bằng key gì đó ah em tìm thử bằng genres thì nó tìm ra các tên truyện có tên giống với key word genres em nhập để tìm kiếm ah

**Comment by pth-1641** [comment]
Ví dụ em tìm truyện "Ô Long Viện" thì em query là "ô long viện", nó sẽ hiển thị đề xuất các truyện có chữ "ô long viện" trong đó

**Comment by Trung123580** [comment]
cái này là tìm truyện tranh theo thể loại đó ah là user chọn 3 thể loại action anime harem thì sẽ call 1api để trả về những truyện có thể loại của user đã chọn

**Comment by Trung123580** [comment]
nó giống với page Tìm Truyện ở NETTRUYEN đó ah 
https://www.nettruyenus.com/tim-truyen-nang-cao
