### ISSUE TITLE
genre id không trùng khớp

### ISSUE THREAD

**Issue by Qhung3217** [pth-1641/Comics-API#13]
**Genre id** trong **comic detail** (`path: /comics/${comic_id}`) **không trùng khớp** với **genre id** trong **genres api** (`path: /genres`)

vd: Thể loại comedy trong comic detail có id là `comedy`, trong genres api là `comedy-99`

**Comment by pth-1641** [comment]
Bạn có thể cho mình xin link của comic bị sai id được k nhỉ

**Comment by Qhung3217** [comment]
Hầu như comic nào cũng bị sai hết. Bạn chọn những comic nào có genre ID mà có kèm theo số ở phía cuối như `comedy-99`, `action-95`,.. là đều bị hết
vd: one piece, Những Ranker Cấp S Mà Tôi Nuôi Dưỡng,...
