### ISSUE TITLE
Không có ảnh truyện để đọc truyện

### ISSUE THREAD

**Issue by nhimc9x** [pth-1641/Comics-API#14]
Do chủ Apis không cho lấy ảnh hay là mình gọi lấy ảnh sai cách nhỉ ?

**Comment by pth-1641** [comment]
Đường dẫn ảnh của của bạn như nào? Mình vừa test thì vẫn xem được ảnh

**Comment by nhimc9x** [comment]
> Đường dẫn của bạn như nào? Mình vừa test thì vẫn xem được ảnh
Ví dụ như vầy: https://comics-api.vercel.app/images?src=https://cdnnvd.com/nettruyen/toi-chi-la-mot-nguoi-don-dep/27/0.jpg

**Comment by pth-1641** [comment]
fixed
