### ISSUE TITLE
không thể lấy dữ liệu truyện

### ISSUE THREAD

**Issue by locnguyenhuu0024** [pth-1641/Comics-API#15]
![Screenshot 2024-05-21 at 15 37 36](https://github.com/pth-1641/Comics-API/assets/68358937/99b62398-4268-4377-8de8-46149b3e4c21)

**Comment by locnguyenhuu0024** [comment]
@pth-1641 bạn có thể kiểm tra xem mọi thứ còn hoạt động bình thường không?

**Comment by pth-1641** [comment]
🐛 Updated new [API](https://github.com/pth-1641/Comics-API/blob/master/README.md)
