### ISSUE TITLE
Không load được ảnh truyện

### ISSUE THREAD

**Issue by locnguyenhuu0024** [pth-1641/Comics-API#8]
<img width="1013" alt="Screenshot 2023-09-24 at 23 17 06" src="https://github.com/pth-1641/Comics-API/assets/68358937/ee98e14d-85fa-42b5-adc2-b35e60725907">

**Comment by Trung123580** [comment]
> <img alt="Ảnh chụp màn hình 2023-09-24 lúc 23 17 06" width="1013" src="https://user-images.githubusercontent.com/68358937/270177473-ee98e14d-85fa-42b5-adc2-b35e60725907.png">

bạn ơi tôi cx giống bạn cái web quan trọng nhất là đọc truyện nhưng giờ nó trống không

**Comment by pth-1641** [comment]
Mình fix + thêm link backup ảnh rồi nhé 
![image](https://github.com/pth-1641/Comics-API/assets/68986796/2b028820-00b5-4115-80aa-fef256eb3b14)

**Comment by Trung123580** [comment]
em có lấy cái này làm bài tập lớn nên anh có thể trong 1 2 tháng tới ổn định cái api được không ah em cảm ơn anh rất nhìu

**Comment by locnguyenhuu0024** [comment]
hiện tại vẫn còn gặp 1 số lỗi khi fetch data

<img width="803" alt="Screenshot 2023-09-25 at 21 05 39" src="https://github.com/pth-1641/Comics-API/assets/68358937/6b703818-9536-44a7-b2d0-50841a7c43e1">

<img width="804" alt="Screenshot 2023-09-25 at 21 07 11" src="https://github.com/pth-1641/Comics-API/assets/68358937/8322efea-f1db-41a7-ae0d-88d4b7ba7719">

**Comment by pth-1641** [comment]
@locnguyenhuu0024 lỗi này do server bên vercel, chứ mình run trên local vẫn ổn

**Comment by Trung123580** [comment]
mất đi 2 trường chapter_name và comic_name thì nó trống không  khi callApi chapters
